Repository sosow0212/ChatUniv, pull requests merged in 2023-10, with the labels that each got.

#70 refactor: 로그인 기능 변경 및 일부 기능 수정
  src/docs/asciidoc/statistic.adoc
  src/main/java/mju/chatuniv/auth/controller/AuthController.java
  src/main/java/mju/chatuniv/auth/service/JwtAuthService.java
  src/main/java/mju/chatuniv/auth/support/JwtLoginResolver.java
  src/main/java/mju/chatuniv/board/controller/BoardController.java
  src/main/java/mju/chatuniv/chat/controller/ChatController.java
  src/main/java/mju/chatuniv/chat/domain/chat/Chat.java
  src/main/java/mju/chatuniv/chat/service/ChatService.java
  src/main/java/mju/chatuniv/chat/service/dto/chat/ChattingHistoryResponse.java
  src/main/java/mju/chatuniv/comment/controller/BoardCommentController.java
  src/main/java/mju/chatuniv/comment/controller/CommentController.java
  src/main/java/mju/chatuniv/member/controller/MemberController.java
  src/main/java/mju/chatuniv/member/controller/dto/MembersBoardResponse.java
  src/main/java/mju/chatuniv/member/controller/dto/MembersChatRoomResponse.java
  src/main/java/mju/chatuniv/member/controller/dto/MembersCommentsResponse.java
  src/main/java/mju/chatuniv/member/exception/MemberExceptionHandler.java
  src/main/java/mju/chatuniv/statistic/controller/StatisticController.java
  src/test/java/mju/chatuniv/chat/controller/ChatControllerIntegrationTest.java
  src/test/java/mju/chatuniv/chat/controller/ChatControllerUnitTest.java
  src/test/java/mju/chatuniv/chat/service/ChatServiceIntegrationTest.java
Labels: 리팩토링

#76 feat: 채팅방 검색 기능 추가
  src/docs/asciidoc/chat.adoc
  src/main/java/mju/chatuniv/chat/controller/ChatController.java
  src/main/java/mju/chatuniv/chat/controller/dto/ConversationAllResponse.java
  src/main/java/mju/chatuniv/chat/infrastructure/dto/ConversationSimpleResponse.java
  src/main/java/mju/chatuniv/chat/infrastructure/repository/ChatQueryRepository.java
  src/main/java/mju/chatuniv/chat/service/ChatQueryService.java
  src/main/java/mju/chatuniv/chat/service/ChatService.java
  src/main/java/mju/chatuniv/chat/service/dto/chat/ChattingHistoryResponse.java
  src/test/java/mju/chatuniv/acceptance/AcceptanceTest.java
  src/test/java/mju/chatuniv/acceptance/ChatAcceptanceTest.java
  src/test/java/mju/chatuniv/chat/controller/ChatControllerUnitTest.java
  src/test/java/mju/chatuniv/chat/service/ChatServiceIntegrationTest.java
Labels: 기능 추가, 리팩토링

#77 feat: 게시판 검색 기능 추가
  src/docs/asciidoc/board.adoc
  src/main/java/mju/chatuniv/board/controller/BoardController.java
  src/main/java/mju/chatuniv/board/controller/dto/BoardAllResponse.java
  src/main/java/mju/chatuniv/board/controller/dto/SearchType.java
  src/main/java/mju/chatuniv/board/domain/BoardRepositoryCustom.java
  src/main/java/mju/chatuniv/board/domain/BoardRepositoryCustomImpl.java
  src/main/java/mju/chatuniv/board/exception/BoardExceptionHandler.java
  src/main/java/mju/chatuniv/board/infrasuructure/dto/BoardPagingResponse.java
  src/main/java/mju/chatuniv/board/infrasuructure/dto/BoardResponse.java
  src/main/java/mju/chatuniv/board/infrasuructure/dto/BoardSearchResponse.java
  src/main/java/mju/chatuniv/board/infrasuructure/repository/BoardQueryRepository.java
  src/main/java/mju/chatuniv/board/infrasuructure/repository/BoardRepository.java
  src/main/java/mju/chatuniv/board/service/BoardQueryService.java
  src/main/java/mju/chatuniv/board/service/BoardService.java
  src/main/java/mju/chatuniv/board/service/dto/BoardCreateRequest.java
  src/main/java/mju/chatuniv/board/service/dto/BoardUpdateRequest.java
  src/main/java/mju/chatuniv/comment/controller/dto/CommentAllResponse.java
  src/main/java/mju/chatuniv/comment/domain/dto/CommentPagingResponse.java
  src/main/java/mju/chatuniv/comment/service/service/BoardCommentService.java
  src/main/java/mju/chatuniv/member/controller/MemberController.java
  src/main/java/mju/chatuniv/member/controller/dto/MembersBoardResponse.java
  src/main/java/mju/chatuniv/member/service/service/MemberService.java
  src/test/java/mju/chatuniv/acceptance/BoardAcceptanceTest.java
  src/test/java/mju/chatuniv/board/controller/BoardControllerIntegrationTest.java
  src/test/java/mju/chatuniv/board/controller/BoardControllerUnitTest.java
  src/test/java/mju/chatuniv/board/service/boardService/BoardServiceIntegrationTest.java
  src/test/java/mju/chatuniv/board/service/boardService/BoardServiceUnitTest.java
  src/test/java/mju/chatuniv/comment/controller/intergration/CommonCommentControllerIntegrationTest.java
  src/test/java/mju/chatuniv/comment/controller/unit/BoardCommentControllerUnitTest.java
  src/test/java/mju/chatuniv/comment/service/integration/CommonCommentServiceIntegrationTest.java
  src/test/java/mju/chatuniv/comment/service/unit/BoardCommentServiceUnitTest.java
  src/test/java/mju/chatuniv/member/controller/MemberControllerIntegrationTest.java
  src/test/java/mju/chatuniv/member/controller/MemberControllerUnitTest.java
  src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
Labels: 기능 추가, 리팩토링

#78 모든 채팅방 조회 기능 추가
  src/docs/asciidoc/chat.adoc
  src/main/java/mju/chatuniv/chat/controller/ChatController.java
  src/main/java/mju/chatuniv/chat/controller/dto/ChatRoomsSimpleResponse.java
  src/main/java/mju/chatuniv/chat/controller/dto/ConversationAllResponse.java
  src/main/java/mju/chatuniv/chat/infrastructure/repository/ChatQueryRepository.java
  src/main/java/mju/chatuniv/chat/infrastructure/repository/dto/ChatRoomSimpleResponse.java
  src/main/java/mju/chatuniv/chat/infrastructure/repository/dto/ConversationSimpleResponse.java
  src/main/java/mju/chatuniv/chat/service/ChatQueryService.java
  src/test/java/mju/chatuniv/acceptance/AcceptanceTest.java
  src/test/java/mju/chatuniv/acceptance/ChatAcceptanceTest.java
  src/test/java/mju/chatuniv/chat/controller/ChatControllerUnitTest.java
  src/test/java/mju/chatuniv/chat/service/ChatServiceIntegrationTest.java
  src/test/java/mju/chatuniv/fixture/chat/ChatFixture.java
Labels: 기능 추가

#80 chore: bootJar 설정 추가
  build.gradle
Labels: 리팩토링, 페어

#85 refactor: flyway 수정
  src/main/resources/db/migration/V1__init.sql
  src/test/java/mju/chatuniv/board/controller/BoardControllerUnitTest.java
Labels: 리팩토링
